### ISSUE TITLE
pgrouting 2.1 has being released

### ISSUE THREAD

**Issue by cvvergara** [nextgis/gis_packages_centos#2]
Hello Maxim and Dimitri:
I released pgrouting 2.1, I would be very pleased if you can make the package for centos
I created this wiki page in our repository about [installation instructions](https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download%2C-Installation-and-building-pgRouting) of pgrouting.
Please feel free to edit the appropriate section.
For future releases I will be using the issue tickets to inform about them.
Thank you 
Vicky Vergara

**Comment by simgislab** [comment]
add some info here: https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download%2C-Installation-and-building-pgRouting#rhelcentosfedora

**Comment by drnextgis** [comment]
@cvvergara, I'm trying to make CentOS package for pgRouting 2.1 but get build error. Could you help me, please.

```
[rpmbuild@rhel SPECS]$ rpmbuild -ba --target=x86_64 pgrouting.spec
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.fnWSfx
+ umask 022
+ cd /home/rpmbuild/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /home/rpmbuild/rpmbuild/BUILD
+ rm -rf pgrouting-2.1.0
+ /bin/tar -xf -
+ /usr/bin/gzip -dc /home/rpmbuild/rpmbuild/SOURCES/pgrouting-2.1.0.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd pgrouting-2.1.0
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ZbFItB
+ umask 022
+ cd /home/rpmbuild/rpmbuild/BUILD
+ cd pgrouting-2.1.0
+ LANG=C
+ export LANG
+ unset DISPLAY
+ install -d build
+ cd build
+ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_VERSION: 2.8.12.2
-- PGROUTING_GIT_TAG: pgrouting-2.1.0
-- PGROUTING_GIT_BUILD: 1
-- PGROUTING_GIT_HASH: b38118a
-- PGROUTING_GIT_BRANCH: master
-- PGROUTING_VERSION_REVISION_NAME: b38118a master
-- PGROUTING_SOURCE_DIR: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0
-- CMAKE_BINARY_DIR: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/build
-- PGROUTING_VERSION_REVISION_HASH: b38118a
-- POSTGRESQL_BIN: 
-- UNIX=1
-- WIN32=
-- Found Perl: /usr/bin/perl (found version "5.10.1") 
-- POSTGRESQL_PG_CONFIG is /usr/local/sbin/pg_config
-- POSTGRESQL_EXECUTABLE is POSTGRESQL_EXECUTABLE-NOTFOUND
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 9.4.5
-- POSTGRESQL_INCLUDE_DIR: /usr/pgsql-9.4/include/server
-- POSTGRESQL_LIBRARIES: /usr/pgsql-9.4/lib
-- Boost version: 1.58.0
-- Boost headers were found here: /usr/include
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
-- CGAL_INCLUDE_DIR=/usr/include
-- CGAL_LIBRARIES=/usr/lib64/libCGAL.so
-- BOOST_THREAD_LIBRARIES=/usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_system-mt.so
-- GMP_LIBRARIES=/usr/lib64/libgmp.so
-- Found CGAL: /usr/include, /usr/lib64/libCGAL.so, /usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_system-mt.so, /usr/lib64/libgmp.so
-- POSTGRESQL_VERSION_STRING is PostgreSQL 9.4.5
-- POSTGRESQL_VERSION is 9.4.5
-- PGSQL_VERSION is 94
-- Install directory for libraries is set to /usr/pgsql-9.4/lib
-- Extension directory for SQL files is set to /usr/pgsql-9.4/share/extension
-- Creating lib/pgrouting--2.1.0.sig
-- LIBS_TO_INSTALL=
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/build
+ /usr/bin/make
Scanning dependencies of target vrppdtw
[  2%] Building C object src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp.c.o
[  5%] Building CXX object src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp_solver.cpp.o
[  5%] Built target vrppdtw
Scanning dependencies of target apsp_johnson
[  7%] Building C object src/apsp_johnson/src/CMakeFiles/apsp_johnson.dir/apsp_johnson.c.o
[ 10%] Building CXX object src/apsp_johnson/src/CMakeFiles/apsp_johnson.dir/apsp_johnson_boost_wrapper.cpp.o
[ 10%] Built target apsp_johnson
Scanning dependencies of target apsp_warshall
[ 12%] Building C object src/apsp_warshall/src/CMakeFiles/apsp_warshall.dir/apsp.c.o
[ 15%] Building CXX object src/apsp_warshall/src/CMakeFiles/apsp_warshall.dir/apsp_boost_wrapper.cpp.o
[ 15%] Built target apsp_warshall
Scanning dependencies of target astar
[ 17%] Building C object src/astar/src/CMakeFiles/astar.dir/astar.c.o
[ 20%] Building CXX object src/astar/src/CMakeFiles/astar.dir/astar_boost_wrapper.cpp.o
[ 20%] Built target astar
Scanning dependencies of target bd_dijkstra
[ 23%] Building C object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/bdsp.c.o
[ 25%] Building CXX object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/bdsp_core.cpp.o
[ 28%] Building CXX object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/BiDirDijkstra.cpp.o
[ 28%] Built target bd_dijkstra
Scanning dependencies of target bd_astar
[ 30%] Building C object src/bd_astar/src/CMakeFiles/bd_astar.dir/bdastar.c.o
[ 33%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/MinHeap.cpp.o
[ 35%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/bdastar_core.cpp.o
[ 38%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/BiDirAStar.cpp.o
[ 38%] Built target bd_astar
Scanning dependencies of target common
[ 41%] Building C object src/common/src/CMakeFiles/common.dir/postgres_connection.c.o
[ 43%] Building CXX object src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o
In file included from /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.cpp:28:
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int collapse_paths(pgr_path_element3_t**, const std::deque<Path, std::allocator<Path> >&)':
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:102: error: expected initializer before ':' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ';' before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ')' before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const Path&, const Path&)':
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before '[' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before ']' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected unqualified-id before 'bool'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:119: error: expected initializer before ':' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ';' at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ')' at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected statement at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected '}' at end of input
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: warning: no return statement in function returning non-void
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const std::deque<Path, std::allocator<Path> >&)':
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:137: error: expected initializer before ':' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ';' before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ')' before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int count_tuples(const std::deque<Path, std::allocator<Path> >&)':
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:145: error: expected initializer before ':' token
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ';' before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
/home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ')' before 'return'
make[2]: *** [src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o] Error 1
make[1]: *** [src/common/src/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.ZbFItB (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.ZbFItB (%build)
```

**Comment by cvvergara** [comment]
I think the c++ compiler needed is 4.7 to be able to use the C++0

On Sat, Oct 17, 2015 at 11:37 AM, Denis Rykov <notifications@github.com>
wrote:

> @cvvergara <https://github.com/cvvergara>, I'm trying to make CentOS
> package for pgRouting 2.1 but get build error. Could you help me, please.
>
> [rpmbuild@rhel SPECS]$ rpmbuild -ba --target=x86_64 pgrouting.spec
> Building target platforms: x86_64
> Building for target x86_64
> Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.fnWSfx
> + umask 022
> + cd /home/rpmbuild/rpmbuild/BUILD
> + LANG=C
> + export LANG
> + unset DISPLAY
> + cd /home/rpmbuild/rpmbuild/BUILD
> + rm -rf pgrouting-2.1.0
> + /bin/tar -xf -
> + /usr/bin/gzip -dc /home/rpmbuild/rpmbuild/SOURCES/pgrouting-2.1.0.tar.gz
> + STATUS=0
> + '[' 0 -ne 0 ']'
> + cd pgrouting-2.1.0
> + /bin/chmod -Rf a+rX,u+w,g-w,o-w .
> + exit 0
> Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ZbFItB
> + umask 022
> + cd /home/rpmbuild/rpmbuild/BUILD
> + cd pgrouting-2.1.0
> + LANG=C
> + export LANG
> + unset DISPLAY
> + install -d build
> + cd build
> + cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
> -- The C compiler identification is GNU 4.4.7
> -- The CXX compiler identification is GNU 4.4.7
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- CMAKE_VERSION: 2.8.12.2
> -- PGROUTING_GIT_TAG: pgrouting-2.1.0
> -- PGROUTING_GIT_BUILD: 1
> -- PGROUTING_GIT_HASH: b38118a
> -- PGROUTING_GIT_BRANCH: master
> -- PGROUTING_VERSION_REVISION_NAME: b38118a master
> -- PGROUTING_SOURCE_DIR: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0
> -- CMAKE_BINARY_DIR: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/build
> -- PGROUTING_VERSION_REVISION_HASH: b38118a
> -- POSTGRESQL_BIN:
> -- UNIX=1
> -- WIN32=
> -- Found Perl: /usr/bin/perl (found version "5.10.1")
> -- POSTGRESQL_PG_CONFIG is /usr/local/sbin/pg_config
> -- POSTGRESQL_EXECUTABLE is POSTGRESQL_EXECUTABLE-NOTFOUND
> -- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 9.4.5
> -- POSTGRESQL_INCLUDE_DIR: /usr/pgsql-9.4/include/server
> -- POSTGRESQL_LIBRARIES: /usr/pgsql-9.4/lib
> -- Boost version: 1.58.0
> -- Boost headers were found here: /usr/include
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   system
> -- CGAL_INCLUDE_DIR=/usr/include
> -- CGAL_LIBRARIES=/usr/lib64/libCGAL.so
> -- BOOST_THREAD_LIBRARIES=/usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_system-mt.so
> -- GMP_LIBRARIES=/usr/lib64/libgmp.so
> -- Found CGAL: /usr/include, /usr/lib64/libCGAL.so, /usr/lib64/libboost_thread-mt.so;/usr/lib64/libboost_system-mt.so, /usr/lib64/libgmp.so
> -- POSTGRESQL_VERSION_STRING is PostgreSQL 9.4.5
> -- POSTGRESQL_VERSION is 9.4.5
> -- PGSQL_VERSION is 94
> -- Install directory for libraries is set to /usr/pgsql-9.4/lib
> -- Extension directory for SQL files is set to /usr/pgsql-9.4/share/extension
> -- Creating lib/pgrouting--2.1.0.sig
> -- LIBS_TO_INSTALL=
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/build
> + /usr/bin/make
> Scanning dependencies of target vrppdtw
> [  2%] Building C object src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp.c.o
> [  5%] Building CXX object src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp_solver.cpp.o
> [  5%] Built target vrppdtw
> Scanning dependencies of target apsp_johnson
> [  7%] Building C object src/apsp_johnson/src/CMakeFiles/apsp_johnson.dir/apsp_johnson.c.o
> [ 10%] Building CXX object src/apsp_johnson/src/CMakeFiles/apsp_johnson.dir/apsp_johnson_boost_wrapper.cpp.o
> [ 10%] Built target apsp_johnson
> Scanning dependencies of target apsp_warshall
> [ 12%] Building C object src/apsp_warshall/src/CMakeFiles/apsp_warshall.dir/apsp.c.o
> [ 15%] Building CXX object src/apsp_warshall/src/CMakeFiles/apsp_warshall.dir/apsp_boost_wrapper.cpp.o
> [ 15%] Built target apsp_warshall
> Scanning dependencies of target astar
> [ 17%] Building C object src/astar/src/CMakeFiles/astar.dir/astar.c.o
> [ 20%] Building CXX object src/astar/src/CMakeFiles/astar.dir/astar_boost_wrapper.cpp.o
> [ 20%] Built target astar
> Scanning dependencies of target bd_dijkstra
> [ 23%] Building C object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/bdsp.c.o
> [ 25%] Building CXX object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/bdsp_core.cpp.o
> [ 28%] Building CXX object src/bd_dijkstra/src/CMakeFiles/bd_dijkstra.dir/BiDirDijkstra.cpp.o
> [ 28%] Built target bd_dijkstra
> Scanning dependencies of target bd_astar
> [ 30%] Building C object src/bd_astar/src/CMakeFiles/bd_astar.dir/bdastar.c.o
> [ 33%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/MinHeap.cpp.o
> [ 35%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/bdastar_core.cpp.o
> [ 38%] Building CXX object src/bd_astar/src/CMakeFiles/bd_astar.dir/BiDirAStar.cpp.o
> [ 38%] Built target bd_astar
> Scanning dependencies of target common
> [ 41%] Building C object src/common/src/CMakeFiles/common.dir/postgres_connection.c.o
> [ 43%] Building CXX object src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o
> In file included from /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.cpp:28:
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int collapse_paths(pgr_path_element3_t**, const std::deque<Path, std::allocator<Path> >&)':
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:102: error: expected initializer before ':' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ';' before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ')' before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const Path&, const Path&)':
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before '[' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before ']' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected unqualified-id before 'bool'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:119: error: expected initializer before ':' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ';' at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ')' at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected statement at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected '}' at end of input
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: warning: no return statement in function returning non-void
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const std::deque<Path, std::allocator<Path> >&)':
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:137: error: expected initializer before ':' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ';' before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ')' before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int count_tuples(const std::deque<Path, std::allocator<Path> >&)':
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:145: error: expected initializer before ':' token
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ';' before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
> /home/rpmbuild/rpmbuild/BUILD/pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ')' before 'return'
> make[2]: *** [src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o] Error 1
> make[1]: *** [src/common/src/CMakeFiles/common.dir/all] Error 2
> make: *** [all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.ZbFItB (%build)
>
>
> RPM build errors:
>     Bad exit status from /var/tmp/rpm-tmp.ZbFItB (%build)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/gis_packages_centos/issues/2#issuecomment-148878970>
> .
>



-- 

Georepublic UG & Georepublic Japan
Mail: vicky@georepublic.deWeb: https://georepublic.info

**Comment by drnextgis** [comment]
Thanks. I've built package and update pgrouting wiki page.

**Comment by cvvergara** [comment]
I am adding your names to the wiki, So I don't forget when I update the
official documentation.
So to confirm the names are correct:
Denis Rykov
Maxim Dubinin

On Sun, Oct 18, 2015 at 3:43 AM, Denis Rykov <notifications@github.com>
wrote:

> Thanks. I've built package and update pgrouting wiki page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/gis_packages_centos/issues/2#issuecomment-148942301>
> .
>



-- 

Georepublic UG & Georepublic Japan
Mail: vicky@georepublic.deWeb: https://georepublic.info

**Comment by drnextgis** [comment]
Confirm, names are correct.

**Comment by cvvergara** [comment]
I sent a mail to pgRouting-dev list and pgrouting-user list with the following content:
"
Thanks to:
Denis Rykov
Maxim Dubinin
pgrouting Version 2.1.0 is ready for Centos.
Instructions on how to get it are detailed in the following link
https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download%2C-Installation-and-building-pgRouting
"

Thanks for your help.
